### ISSUE TITLE
CPU-intensive analysis operation are accelerated using multi-threading

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1292]
On a particular data set:

```
Indexing AppMaps...
Indexed 310 AppMaps in 9469ms
Generating sequence diagrams...
Generated 310 sequence diagrams in 31448ms
Generating OpenAPI...
Generated OpenAPI in 5134ms
Scanning...
Scanned 310 AppMaps in 186645ms
```

Indexing is less than 10 seconds, so in this situation, it probably can't be accelerated further. OpenAPI generation is similar.

Sequence diagrams takes 30s. 

Scanning takes 186s, it's the slowest by a factor of 6.

**Comment by kgilpin** [comment]
When _appmap-scanner.yml_ is reduced, it takes only 30s:

```
checks:
  - rule: n-plus-one-query
  - rule: slow-function-call
    properties:
      timeAllowed: 5
  - rule: slow-http-server-request
    properties:
      timeAllowed: 5
  - rule: slow-query
    properties:
      timeAllowed: 5
```
