### ISSUE TITLE
AppMap installation to Gradle 9 is not properly formed

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1441]
![IMG_3434](https://github.com/getappmap/appmap-js/assets/86395/6b33bca8-82bf-4ace-970d-529059ad5581)

**Comment by dustinbyrne** [comment]
If this is failing inside the install action it seems like the installer would need to detect [spotless](https://github.com/diffplug/spotless) (among, potentially other future formatters/linters) and conditionally run `spotlessApply`/`spotless:apply` to fix any potential violations.

If it's occurring between steps it should be possible to add a step to run the formatter. Though I'm assuming that this is not the case.
```yml
  - name: Install AppMap tools
    id: install-appmap
    uses: getappmap/install-action@v1
    with:
      project-type: npm
      build-patch-file: false

  - run: ./gradlew spotlessApply

  - name: Commit changes
    uses: EndBug/add-and-commit@v9
```
