### ISSUE TITLE
Installer: Java installer does not recognize packages in multi-module projects

### ISSUE THREAD

**Issue by ptrdvrk** [getappmap/appmap-js#460]
[WebGoat](https://github.com/land-of-apps/WebGoat) is a good example of this problem. The installer updates pom.xml correctly and generates `appmap.yml` that has no packages without giving the user any warning that no packages were found and added to the configuration.
```yaml
# This is the AppMap configuration file.
# For full documentation of this file for Java programs, see:
# https://appland.com/docs/reference/appmap-java.html#configuration
name: WebGoat
packages: []
# appmap-java init looks for source packages in src/main/java.
# This folder was not found in your project, so no packages were auto-detected.
# You can add your source packages by replacing the line above with lines like this:
# packages:
# - path: com.mycorp.pkg
# - path: org.otherstuff.pkg
```

The installer should at least notify the user that the appmap.yml configuration is incomplete; and preferably the logic for discovering Java packages is updated to search for sources in the projects' submodules' folders.

```
~/work/github/java/WebGoat • develop*
‣ npx appmap install
? This directory contains sub-projects. Would you like to choose sub-projects for installation? No
Installing AppMap agent for ....
? AppMap is about to be installed. Confirm the details below.
  Project type: Maven
  Project directory: /Users/ptrdvrk/work/github/java/WebGoat
  Git remote: origin	https://github.com/WebGoat/WebGoat.git (fetch)
  JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
  JDK Version: 11.0.10

  Is this correct? Yes
? An appmap.yml configuration file already exists. How should the conflict be resolved? Overwrite
✔ Installing the AppMap agent...
✔ Validating the AppMap agent...

   ╭────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                    │
   │                   Success! The AppMap agent has been installed.                    │
   │                                                                                    │
   │   The AppMap agent will automatically record your tests when you run ./mvnw test   │
   │              By default, AppMap files will be output to target/appmap              │
   │                                                                                    │
   │                            For more information, visit                             │
   │                   https://appland.com/docs/reference/appmap-java                   │
   │                                                                                    │
   ╰────────────────────────────────────────────────────────────────────────────────────╯
```
